#
# Copyright 2018-2019, Ridecell, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
apiVersion: v1
kind: Namespace
metadata:
  name: ridecell-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ridecell-operator
  namespace: ridecell-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ridecell-operator
rules:
- apiGroups: [""]
  resources: [configmaps, events, services, secrets, persistentvolumeclaims ]
  verbs: ["*"]
- apiGroups: [policy]
  resources: [poddisruptionbudgets]
  verbs: ["*"]
- apiGroups: [""]
  resources: [pods]
  verbs: [watch, list, delete]
- apiGroups: [""]
  resources: [nodes]
  verbs: [watch, list, get]
- apiGroups: [extensions]
  resources: [ingresses]
  verbs: ["*"]
- apiGroups: [apps]
  resources: [deployments, statefulsets]
  verbs: ["*"]
- apiGroups: [batch]
  resources: [jobs]
  verbs: ["*"]
- apiGroups: [acid.zalan.do]
  resources: [postgresqls]
  verbs: ["*"]
- apiGroups: [monitoring.coreos.com]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [summon.ridecell.io]
  resources: ["*"]
  verbs: [get, list, watch, update]
- apiGroups: [summon.ridecell.io]
  resources: [mockcarservertenants, djangousers, djangousers/status]
  verbs: ["*"]
- apiGroups: [secrets.ridecell.io, db.ridecell.io, aws.ridecell.io, monitoring.ridecell.io, ingress.ridecell.io, gcp.ridecell.io]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [apiextensions.k8s.io]
  resources: [customresourcedefinitions]
  verbs: [get, list, create, update]
- apiGroups: [autoscaling]
  resources: [horizontalpodautoscalers]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ridecell-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ridecell-operator
subjects:
- name: ridecell-operator
  namespace: ridecell-operator
  kind: ServiceAccount
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ridecell-operator
  namespace: ridecell-operator
spec:
  selector:
    matchLabels:
      app: ridecell-operator
  template:
    metadata:
      labels:
        app: ridecell-operator
    spec:
      serviceAccountName: ridecell-operator
      imagePullSecrets:
      - name: pull-secret
      initContainers:
      - name: install-crds
        image: us.gcr.io/ridecell-1/ridecell-operator:2029-00e3d8a-master
        command: [/install_crds, /crds, -v, "4", -logtostderr]
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      containers:
      - name: default
        image: us.gcr.io/ridecell-1/ridecell-operator:2029-00e3d8a-master
        command: [/ridecell-operator, -v, "4", -logtostderr]
        resources:
          limits:
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
          - name: AWS_REGION
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['ridecell.io/cloud-region']
          - name: AWS_SUBNET_GROUP_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['ridecell.io/cluster-name']
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/run/secrets/gcp-service-account/google_service_account.json
        envFrom:
        - secretRef:
            name: ridecell-operator
        volumeMounts:
        - name: secrets
          mountPath: /var/run/secrets/gcp-service-account/google_service_account.json
          subPath: GOOGLE_SERVICE_ACCOUNT_KEY
      volumes:
      - name: secrets
        secret:
          secretName: ridecell-operator
      terminationGracePeriodSeconds: 10
---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: ridecell-operator
#   namespace: ridecell-operator
# stringData:
#   slackApiKey:
#   operatorAwsAccessKeyId:
#   operatorAwsSecretAccessKey:
#   awsRegion:
#   permissionsBoundaryArn:
---
